versions:
  "2":
    build_args:
      AZURE_CLI: 2.4.0
      TERRAFORM_VERSION: 0.12.24
    test_config:
      cmd:
        - az --version
        - terraform --version
    template_vars:
      BASE_IMAGE_VERSION: 3.8
